# Generated by Django 4.2.7 on 2024-11-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('cpfCnpj', models.CharField(max_length=100)),
                ('numTelefone', models.CharField(blank=True, max_length=100)),
                ('tipUsuario', models.CharField(choices=[('A', 'Admin'), ('C', 'Cliente'), ('F', 'Funcionário')], default='C', max_length=1)),
            ],
        ),
    ]
