# Generated by Django 4.2.7 on 2024-11-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_backend', '0002_carrinho_categoriaproduto_formapagamento_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='parcelas',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
