# Generated by Django 4.2.7 on 2024-11-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_backend', '0003_alter_formapagamento_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscarrinho',
            name='codigoCarrinho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='application_backend.carrinho'),
        ),
    ]
