# Generated by Django 4.2.7 on 2024-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_backend', '0004_alter_itenscarrinho_codigocarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenscarrinho',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
