# Generated by Django 4.2.7 on 2024-11-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_backend', '0005_itenscarrinho_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='staPedido',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='P', max_length=1),
        ),
    ]
