# Generated by Django 4.2.7 on 2024-11-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_backend', '0006_carrinho_stapedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='staPedido',
            new_name='statusPedido',
        ),
    ]
