# Generated by Django 4.2.7 on 2024-11-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_backend', '0007_rename_stapedido_carrinho_statuspedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valorPromocional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
