# Generated by Django 4.2.7 on 2024-11-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_backend', '0008_produto_valorpromocional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipUsuario',
            new_name='tipoUsuario',
        ),
    ]
