# Generated by Django 4.2.7 on 2024-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_backend', '0009_rename_tipusuario_usuario_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpfCnpj',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numTelefone',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
